from aiogram import F
from aiogram.types import Message, KeyboardButton
from aiogram.utils.keyboard import ReplyKeyboardBuilder
from modules.profile.texts import get_text
from modules.database.db import get_user_language  # Импортируем функцию для получения языка пользователя
import random

# Список случайных советов
ADVICES = {
    "en": [
        "Trust your instincts today—they won't let you down.",
        "Take a step back and reassess your goals.",
        "A small act of kindness can change someone's day.",
        "Focus on what truly matters to you.",
        "Embrace change—it often leads to growth.",
        "Don't be afraid to ask for help when needed.",
        "Celebrate small victories—they add up to big successes.",
        "Keep learning; knowledge is your greatest ally.",
        "Stay positive, even in challenging times.",
        "Believe in yourself—you are capable of great things.",
        "Be patient; good things come to those who wait.",
        "Take time to appreciate the little things in life.",
        "Surround yourself with people who uplift you.",
        "Challenge yourself to try something new today.",
        "Remember to take breaks—it boosts productivity.",
        "Focus on progress, not perfection.",
        "Practice gratitude daily—it changes your mindset.",
        "Listen to your body—it knows what you need.",
        "Step out of your comfort zone—it's where growth happens.",
        "Be kind to yourself—you're doing your best.",
        "A simple solution can solve a complex problem.",
        "Let go of past mistakes—they don’t define you.",
        "A heartfelt conversation can strengthen a bond.",
        "Your optimism will attract positive energy.",
        "A forgotten goal can reignite your passion.",
        "A new path can lead to exciting adventures.",
        "Your actions can inspire others to dream bigger.",
        "A quiet moment can bring profound insight.",
        "A small change can lead to significant growth.",
        "A kind word can mend a broken relationship.",
        "Your vision will guide you toward fulfillment.",
        "A new idea can lead to innovative solutions.",
        "Your dedication will inspire others to follow.",
        "A simple choice can lead to immense satisfaction.",
        "A random event can bring unexpected happiness.",
        "Your determination will lead to ultimate victory.",
        "A small gesture can have a profound effect.",
        "A new connection can lead to lasting friendships.",
        "Your confidence will attract positive outcomes.",
        "A simple action can create a lasting impact.",
        "A forgotten talent can resurface and amaze you.",
        "A new chapter is about to begin in your life.",
        "Your efforts will inspire others to follow suit.",
        "A small sacrifice can lead to a big reward.",
        "A stranger’s advice can be surprisingly valuable.",
        "Your creativity will shine brightly today.",
        "A fresh perspective can solve an old problem.",
        "A new opportunity will knock on your door soon.",
        "Your resilience will inspire others around you.",
        "A little courage will go a long way today.",
        "A thoughtful word can brighten someone’s day.",
        "Your perseverance will lead to eventual success.",
        "A hidden talent will surface unexpectedly.",
        "A chance encounter will change your perspective.",
        "Your positivity will attract good fortune.",
        "A small effort will yield great results.",
        "A forgotten dream will rekindle your passion.",
        "A new path will lead to personal growth.",
        "Your actions will inspire others to act.",
        "A quiet moment will bring inner peace.",
        "A small change will lead to a brighter future.",
        "A kind word will heal a wounded heart.",
        "Your vision will guide you through uncertainty.",
        "A new idea will spark a chain reaction.",
        "Your dedication will lead to remarkable achievements.",
        "A simple choice will lead to unexpected joy.",
        "A random event will bring unexpected luck.",
        "Your faith will guide you through tough times.",
        "A small step will lead to a giant leap.",
        "A forgotten memory will bring a smile to your face.",
        "A new opportunity will test your limits.",
        "Your courage will inspire others to act.",
        "A quiet moment will reveal hidden truths.",
        "A small effort will lead to a big transformation.",
        "A new connection will lead to lasting friendships.",
        "Your optimism will light up the room.",
        "A simple act will create a lasting impact.",
        "A forgotten goal will reignite your motivation.",
        "A new challenge will uncover hidden strengths.",
        "Your resilience will pave the way for success.",
        "A random event will bring unexpected happiness.",
        "Your determination will lead to ultimate victory.",
        "A small gesture will have a profound effect.",
        "A new path will lead to personal growth.",
        "Your actions will inspire others to dream bigger.",
        "A quiet moment will bring inner peace.",
        "A small change will lead to a brighter future.",
        "A kind word will mend a broken relationship.",
        "Your vision will guide you toward fulfillment.",
        "A new idea will lead to innovative solutions.",
        "Your dedication will inspire others to follow.",
        "A simple choice will lead to immense satisfaction."
    ],
    "ru": [
        "Доверьтесь своей интуиции сегодня — она не подведёт.",
        "Отступите на шаг назад и переоцените свои цели.",
        "Маленький акт доброты может изменить чей-то день.",
        "Сосредоточьтесь на том, что действительно важно для вас.",
        "Примите перемены — они часто ведут к росту.",
        "Не бойтесь просить о помощи, когда это необходимо.",
        "Отмечайте маленькие победы — они складываются в большие успехи.",
        "Продолжайте учиться; знания — ваш самый надёжный союзник.",
        "Оставайтесь позитивными, даже в трудные времена.",
        "Верьте в себя — вы способны на великие дела.",
        "Будьте терпеливы; хорошее приходит к тем, кто ждёт.",
        "Найдите время, чтобы оценить мелочи жизни.",
        "Окружите себя людьми, которые вдохновляют вас.",
        "Победите себя попробовать что-то новое сегодня.",
        "Помните, что перерывы повышают продуктивность.",
        "Сосредоточьтесь на прогрессе, а не на совершенстве.",
        "Практикуйте благодарность ежедневно — это меняет мышление.",
        "Слушайте своё тело — оно знает, что вам нужно.",
        "Выйдите из зоны комфорта — там происходит рост.",
        "Будьте добры к себе — вы делаете всё возможное.",
        "Простое решение может решить сложную проблему.",
        "Отпустите прошлые ошибки — они не определяют вас.",
        "Сердечный разговор может укрепить связь.",
        "Ваш оптимизм привлечёт положительную энергию.",
        "Забытая цель снова разожжёт вашу страсть.",
        "Новый путь приведёт к захватывающим приключениям.",
        "Ваши действия вдохновят других мечтать больше.",
        "Тихий момент принесёт глубокое понимание.",
        "Небольшое изменение приведёт к значительному росту.",
        "Добрые слова исцелят разбитые отношения.",
        "Ваше видение приведёт вас к самореализации.",
        "Новая идея приведёт к инновационным решениям.",
        "Ваша преданность вдохновит других следовать за вами.",
        "Простой выбор приведёт к глубокому удовлетворению.",
        "Случайное событие принесёт неожиданное счастье.",
        "Ваше упорство приведёт к окончательной победе.",
        "Небольшой жест окажет глубокое влияние.",
        "Новое знакомство приведёт к долгим дружбам.",
        "Ваша уверенность привлечёт позитивные результаты.",
        "Простое действие создаст длительный эффект.",
        "Забытый талант снова проявится и удивит вас.",
        "Новая глава вот-вот начнётся в вашей жизни.",
        "Ваши усилия вдохновят других следовать вашему примеру.",
        "Небольшая жертва приведёт к большой награде.",
        "Совет незнакомца может оказаться удивительно ценным.",
        "Ваша креативность сегодня засияет ярко.",
        "Новый взгляд решит старую проблему.",
        "Новая возможность скоро постучится в вашу дверь.",
        "Ваша стойкость вдохновит окружающих.",
        "Немного смелости сегодня сделает многое.",
        "Добрые слова осветят чей-то день.",
        "Ваше упорство приведёт к успеху.",
        "Скрытый талант проявится неожиданно.",
        "Случайная встреча изменит ваш взгляд.",
        "Ваш позитив привлечёт удачу.",
        "Небольшое усилие принесёт великие результаты.",
        "Забытая мечта снова разожжёт вашу страсть.",
        "Новый путь приведёт к личностному росту.",
        "Ваши действия вдохновят других действовать.",
        "Тихий момент принесёт внутренний покой.",
        "Небольшое изменение приведёт к светлому будущему.",
        "Добрые слова исцелят раненное сердце.",
        "Ваше видение проведёт вас через неопределённость.",
        "Новая идея вызовет цепную реакцию.",
        "Ваша преданность приведёт к замечательным достижениям.",
        "Простой выбор приведёт к неожиданной радости.",
        "Случайное событие принесёт неожиданную удачу.",
        "Ваша вера проведёт вас через трудные времена.",
        "Небольшой шаг приведёт к гигантскому скачку.",
        "Забытое воспоминание вызовет улыбку на вашем лице.",
        "Новая возможность проверит ваши пределы.",
        "Ваша храбрость вдохновит других действовать.",
        "Тихий момент откроет скрытые истины.",
        "Небольшое усилие приведёт к большому преображению.",
        "Новое знакомство приведёт к долгим дружбам.",
        "Ваш оптимизм осветит комнату.",
        "Простой поступок создаст длительный эффект.",
        "Забытая цель снова разожжёт вашу мотивацию.",
        "Новое испытание раскроет скрытые силы.",
        "Ваша стойкость проложит путь к успеху.",
        "Случайное событие принесёт неожиданное счастье.",
        "Ваше упорство приведёт к окончательной победе.",
        "Небольшой жест окажет глубокое влияние.",
        "Новый путь приведёт к личностному росту.",
        "Ваши действия вдохновят других мечтать больше.",
        "Тихий момент принесёт внутренний покой.",
        "Небольшое изменение приведёт к светлому будущему.",
        "Добрые слова исцелят разбитые отношения.",
        "Ваше видение приведёт вас к самореализации.",
        "Новая идея приведёт к инновационным решениям.",
        "Ваша преданность вдохновит других следовать за вами.",
        "Простой выбор приведёт к глубокому удовлетворению."
    ]
}


# Обработчик кнопки "Случайный совет"
async def random_advice(message: Message):
    user_id = message.chat.id
    # Получаем язык пользователя через функцию get_user_language
    user_language = get_user_language(user_id) or "ru"  # По умолчанию язык 'ru'

    # Выбираем случайный совет
    advice = random.choice(ADVICES[user_language])

    # Создаём клавиатуру с кнопкой "Назад в меню"
    keyboard = ReplyKeyboardBuilder()
    keyboard.add(
        KeyboardButton(text=get_text(user_language, "back_to_menu"))
    )
    keyboard.adjust(2)

    # Отправляем сообщение с советом
    await message.answer(advice, reply_markup=keyboard.as_markup(resize_keyboard=True))