from aiogram import F
from aiogram.types import Message, KeyboardButton
from aiogram.utils.keyboard import ReplyKeyboardBuilder
from modules.profile.texts import get_text
from modules.database.db import get_user_language  # Импортируем функцию получения языка
import random

# Список предсказаний для "Колеса судьбы"
PREDICTIONS = {
    "en": [
        "Fate says: Today is the day for new beginnings!",
        "Fate says: Be cautious with new acquaintances.",
        "Fate says: Your intuition will guide you to the right decision.",
        "Fate says: A pleasant surprise awaits you today.",
        "Fate says: Stay open to unexpected opportunities.",
        "Fate says: Success is within your reach—keep pushing forward.",
        "Fate says: Take time to reflect on your recent choices.",
        "Fate says: A trusted friend will offer valuable advice soon.",
        "Fate says: Embrace challenges—they are opportunities in disguise.",
        "Fate says: Trust the process; everything will fall into place.",
        "Fate says: Your hard work will soon pay off.",
        "Fate says: A creative idea will inspire you today.",
        "Fate says: Be patient; good things come to those who wait.",
        "Fate says: A new friendship will bring joy into your life.",
        "Fate says: Focus on what truly matters to you.",
        "Fate says: Don't be afraid to take risks—it leads to growth.",
        "Fate says: A small act of kindness will change someone's day.",
        "Fate says: Celebrate small victories—they add up to big successes.",
        "Fate says: Keep learning; knowledge is your greatest ally.",
        "Fate says: Stay positive, even in challenging times.",
        "Fate says: The universe has a plan for you—trust it.",
        "Fate says: A hidden opportunity will reveal itself soon.",
        "Fate says: Your efforts will be recognized and rewarded.",
        "Fate says: Change is coming, but it will be for the better.",
        "Fate says: A long-lost connection will reach out to you.",
        "Fate says: Believe in yourself—you are stronger than you think.",
        "Fate says: A breakthrough is just around the corner.",
        "Fate says: You are destined for greatness—keep going.",
        "Fate says: A chance meeting will lead to something meaningful.",
        "Fate says: Let go of the past—it’s time to move forward.",
        "Fate says: Your dreams are closer than they appear.",
        "Fate says: A simple solution will solve a complex problem.",
        "Fate says: Someone is thinking of you fondly today.",
        "Fate says: A bold step will open new doors for you.",
        "Fate says: Your optimism will attract positive energy.",
        "Fate says: A forgotten goal will resurface and inspire you.",
        "Fate says: A challenge will help you discover your true strength.",
        "Fate says: An unexpected gift will brighten your day.",
        "Fate says: Your patience will be rewarded sooner than expected.",
        "Fate says: A new hobby will bring unexpected joy.",
        "Fate says: A wise decision will lead to future success.",
        "Fate says: Trust your instincts—they rarely lead you astray.",
        "Fate says: A quiet moment will bring clarity to your thoughts.",
        "Fate says: A small sacrifice will lead to a big reward.",
        "Fate says: A stranger will offer you valuable advice.",
        "Fate says: Your creativity will shine brightly today.",
        "Fate says: A fresh perspective will solve an old problem.",
        "Fate says: A new opportunity will knock on your door soon.",
        "Fate says: Your resilience will inspire others around you.",
        "Fate says: A little courage will go a long way today.",
        "Fate says: A heartfelt conversation will strengthen a bond.",
        "Fate says: Your generosity will return to you tenfold.",
        "Fate says: A difficult situation will teach you an important lesson.",
        "Fate says: A random act of kindness will make a difference.",
        "Fate says: Your determination will overcome any obstacle.",
        "Fate says: A surprise message will lift your spirits.",
        "Fate says: A forgotten talent will resurface and amaze you.",
        "Fate says: A new chapter is about to begin in your life.",
        "Fate says: Your efforts will inspire others to follow suit.",
        "Fate says: A small gesture will have a big impact.",
        "Fate says: A new friendship will enrich your life.",
        "Fate says: Your confidence will attract positive outcomes.",
        "Fate says: A simple action will create a ripple effect.",
        "Fate says: A thoughtful word will brighten someone’s day.",
        "Fate says: Your perseverance will lead to eventual success.",
        "Fate says: A hidden talent will surface unexpectedly.",
        "Fate says: A chance encounter will change your perspective.",
        "Fate says: Your positivity will attract good fortune.",
        "Fate says: A small effort will yield great results.",
        "Fate says: A forgotten dream will rekindle your passion.",
        "Fate says: A new path will lead to exciting adventures.",
        "Fate says: Your actions will inspire others to act.",
        "Fate says: A quiet moment will bring profound insight.",
        "Fate says: A small change will lead to significant growth.",
        "Fate says: A kind word will heal a wounded heart.",
        "Fate says: Your vision will guide you through uncertainty.",
        "Fate says: A new idea will spark a chain reaction.",
        "Fate says: Your dedication will lead to remarkable achievements.",
        "Fate says: A simple choice will lead to unexpected joy.",
        "Fate says: A random event will bring unexpected luck.",
        "Fate says: Your faith will guide you through tough times.",
        "Fate says: A small step will lead to a giant leap.",
        "Fate says: A forgotten memory will bring a smile to your face.",
        "Fate says: A new opportunity will test your limits.",
        "Fate says: Your courage will inspire others to act.",
        "Fate says: A quiet moment will reveal hidden truths.",
        "Fate says: A small effort will lead to a big transformation.",
        "Fate says: A new connection will lead to lasting friendships.",
        "Fate says: Your optimism will light up the room.",
        "Fate says: A simple act will create a lasting impact.",
        "Fate says: A forgotten goal will reignite your motivation.",
        "Fate says: A new challenge will uncover hidden strengths.",
        "Fate says: Your resilience will pave the way for success.",
        "Fate says: A random event will bring unexpected happiness.",
        "Fate says: Your determination will lead to ultimate victory.",
        "Fate says: A small gesture will have a profound effect.",
        "Fate says: A new path will lead to personal growth.",
        "Fate says: Your actions will inspire others to dream bigger.",
        "Fate says: A quiet moment will bring inner peace.",
        "Fate says: A small change will lead to a brighter future.",
        "Fate says: A kind word will mend a broken relationship.",
        "Fate says: Your vision will guide you toward fulfillment.",
        "Fate says: A new idea will lead to innovative solutions.",
        "Fate says: Your dedication will inspire others to follow.",
        "Fate says: A simple choice will lead to immense satisfaction."
    ],
    "ru": [
        "Судьба говорит: сегодня — день для новых начинаний!",
        "Судьба говорит: будьте осторожны с новыми знакомствами.",
        "Судьба говорит: ваша интуиция подскажет правильное решение.",
        "Судьба говорит: сегодня вас ждёт приятный сюрприз.",
        "Судьба говорит: будьте открыты неожиданным возможностям.",
        "Судьба говорит: успех находится в пределах вашей досягаемости — продолжайте двигаться вперёд.",
        "Судьба говорит: найдите время, чтобы обдумать свои последние решения.",
        "Судьба говорит: доверенный друг скоро предложит вам ценный совет.",
        "Судьба говорит: примите вызовы — они скрывают в себе возможности.",
        "Судьба говорит: доверьтесь процессу; всё сложится как надо.",
        "Судьба говорит: ваши усилия скоро принесут плоды.",
        "Судьба говорит: творческая идея вдохновит вас сегодня.",
        "Судьба говорит: будьте терпеливы; хорошее приходит к тем, кто ждёт.",
        "Судьба говорит: новая дружба принесёт радость в вашу жизнь.",
        "Судьба говорит: сосредоточьтесь на том, что действительно важно для вас.",
        "Судьба говорит: не бойтесь рисковать — это ведёт к росту.",
        "Судьба говорит: маленький акт доброты может изменить чей-то день.",
        "Судьба говорит: отмечайте маленькие победы — они складываются в большие успехи.",
        "Судьба говорит: продолжайте учиться; знания — ваш самый надёжный союзник.",
        "Судьба говорит: оставайтесь позитивными, даже в трудные времена.",
        "Судьба говорит: у вселенной есть план для вас — доверьтесь ему.",
        "Судьба говорит: скрытая возможность скоро откроется вам.",
        "Судьба говорит: ваши усилия будут замечены и вознаграждены.",
        "Судьба говорит: перемены грядут, но они будут к лучшему.",
        "Судьба говорит: давний контакт скоро свяжется с вами.",
        "Судьба говорит: верьте в себя — вы сильнее, чем думаете.",
        "Судьба говорит: прорыв уже близко.",
        "Судьба говорит: вы предназначены для великих дел — продолжайте.",
        "Судьба говорит: случайная встреча приведёт к чему-то значимому.",
        "Судьба говорит: отпустите прошлое — пора двигаться вперёд.",
        "Судьба говорит: ваши мечты ближе, чем кажутся.",
        "Судьба говорит: простое решение решит сложную проблему.",
        "Судьба говорит: кто-то сегодня тепло о вас думает.",
        "Судьба говорит: смелый шаг откроет перед вами новые двери.",
        "Судьба говорит: ваш оптимизм привлечёт положительную энергию.",
        "Судьба говорит: забытая цель снова всплывёт и вдохновит вас.",
        "Судьба говорит: испытание поможет вам открыть свою истинную силу.",
        "Судьба говорит: неожиданный подарок осветит ваш день.",
        "Судьба говорит: ваше терпение будет вознаграждено быстрее, чем вы думаете.",
        "Судьба говорит: новое хобби принесёт неожиданную радость.",
        "Судьба говорит: мудрое решение приведёт к будущему успеху.",
        "Судьба говорит: доверьтесь своей интуиции — она редко подводит.",
        "Судьба говорит: тихий момент принесёт ясность в ваши мысли.",
        "Судьба говорит: небольшая жертва приведёт к большой награде.",
        "Судьба говорит: незнакомец предложит вам ценный совет.",
        "Судьба говорит: ваша креативность сегодня засияет ярко.",
        "Судьба говорит: новый взгляд решит старую проблему.",
        "Судьба говорит: новая возможность скоро постучится в вашу дверь.",
        "Судьба говорит: ваша стойкость вдохновит окружающих.",
        "Судьба говорит: немного смелости сегодня сделает многое.",
        "Судьба говорит: сердечный разговор укрепит связь.",
        "Судьба говорит: ваша щедрость вернётся к вам сторицей.",
        "Судьба говорит: сложная ситуация научит вас важному уроку.",
        "Судьба говорит: случайный акт доброты сделает разницу.",
        "Судьба говорит: ваше упорство преодолеет любые препятствия.",
        "Судьба говорит: неожиданное сообщение поднимет вам настроение.",
        "Судьба говорит: забытый талант снова проявится и удивит вас.",
        "Судьба говорит: новая глава вот-вот начнётся в вашей жизни.",
        "Судьба говорит: ваши усилия вдохновят других следовать вашему примеру.",
        "Судьба говорит: небольшой жест окажет большое влияние.",
        "Судьба говорит: новая дружба обогатит вашу жизнь.",
        "Судьба говорит: ваша уверенность привлечёт позитивные результаты.",
        "Судьба говорит: простое действие создаст эффект домино.",
        "Судьба говорит: добрые слова осветят чей-то день.",
        "Судьба говорит: ваше упорство приведёт к успеху.",
        "Судьба говорит: скрытый талант проявится неожиданно.",
        "Судьба говорит: случайная встреча изменит ваш взгляд.",
        "Судьба говорит: ваш позитив привлечёт удачу.",
        "Судьба говорит: небольшое усилие принесёт великие результаты.",
        "Судьба говорит: забытая мечта снова разожжёт вашу страсть.",
        "Судьба говорит: новый путь приведёт к захватывающим приключениям.",
        "Судьба говорит: ваши действия вдохновят других мечтать больше.",
        "Судьба говорит: тихий момент принесёт внутренний покой.",
        "Судьба говорит: небольшое изменение приведёт к светлому будущему.",
        "Судьба говорит: добрые слова исцелят разбитые отношения.",
        "Судьба говорит: ваше видение приведёт вас к самореализации.",
        "Судьба говорит: новая идея приведёт к инновационным решениям.",
        "Судьба говорит: ваша преданность вдохновит других следовать за вами.",
        "Судьба говорит: простой выбор приведёт к глубокому удовлетворению."
    ]
}


# Обработчик кнопки "Колесо судьбы"
async def wheel_of_fate(message: Message):
    user_id = message.chat.id
    # Получаем язык пользователя через функцию get_user_language
    user_language = get_user_language(user_id) or "ru"  # По умолчанию язык 'ru'

    # Выбираем случайное предсказание
    prediction = random.choice(PREDICTIONS[user_language])

    # Создаём клавиатуру с кнопкой "Назад в меню"
    keyboard = ReplyKeyboardBuilder()
    keyboard.add(
        KeyboardButton(text=get_text(user_language, "back_to_menu"))
    )
    keyboard.adjust(2)

    # Отправляем сообщение с предсказанием
    await message.answer(prediction, reply_markup=keyboard.as_markup(resize_keyboard=True))